[tool.poetry]
name = "ylva"
version = "0.2.0"
description = "Ylva integrates with YNAB and lets you automate actions"
authors = ["Eleanor Young <developer@nausicaea.net>"]

[tool.poetry.scripts]
ylva = 'ylva.bin.ylva:main'

[tool.poetry.extras]
progress = ["tqdm"]

[tool.poetry.dependencies]
python = "3.14.7"
reidun = {git = "https://github.com/nausicaea/reidun.git", tag = "v0.6.0"}
aiohttp = "3.14.1"
appdirs = "1.4.4"
mashumaro = {version = "3.22", extras = ["yaml"]}
tqdm = {version = "4.68.4", optional = true}
rich = "15.0.0"
ofxstatement = "0.9.3"
ofxstatement-iso20022 = "0.8.1"
ofxstatement-bkb = {git = "https://github.com/nausicaea/ofxstatement-bkb.git"}

[tool.poetry.dev-dependencies]
pytest = "9.1.1"
pytest-asyncio = "1.4.0"

[build-system]
requires = ["poetry-core==2.4.1"]
build-backend = "poetry.core.masonry.api"
